# Site info
title: Kae So Bu
description: Kae So Bu - independent novelist and short story writer of LGBTQ+ and Boyslove romantic fiction
site-email: kaesobu@gmail.com
web-email: kaesobu@googlemail.com

# Site settings
sass:
    sass_dir: _sass

permalink: /journal/:year/:month/:title

plugins:
  - jekyll-paginate

paginate: 2
paginate_path: "/journal/page:num/"

# Handling Books
collections:
  books:
    output: true