# Site info
title: Kae So Bu
description: Kae So Bu - independent novelist and short story writer of LGBTQ+ and Boyslove romantic fiction
site-email: kaesobu@gmail.com
web-email: kaesobu@googlemail.com